site_name: Scikit-garden
site_description: 'Documentation for scikit-garden'
pages:
  - Home: index.md
  - API Reference: api.md
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math
theme: readthedocs
